### ISSUE TITLE
Cannot read property 'values' of undefined

### ISSUE THREAD

**Issue by sudoloic** [yariksav/vuetify-confirm#20]
Hello,

it seems `this.$vuetify.icons` is undefined as I get the error `cannot read property 'values' of undefined`.

    [...]
    import vuetify from './plugins/vuetify';
    import VuetifyConfirm from 'vuetify-confirm'

    Vue.use(VuetifyConfirm, {
      vuetify
    })

    new Vue({
      router,
      store,
      vuetify,
      render: h => h(App)
    }).$mount('#app')

Am i doing something wrong ? 

Using vuetify2, vuetify-confirm@2.0.0 and font awesome icons if that is of any help

**Comment by sudoloic** [comment]
Ok, I fixed it with : 

    Vue.use(VuetifyConfirm, {
      vuetify: vuetify
    })

**Comment by VictorioBerra** [comment]
Same issue. That does not fix it. Neither does Vue.use(VuetifyConfirm, { $vuetify: veutifyObj.framework })

**Comment by VictorioBerra** [comment]
I needed:

```javascript
import Vue from 'vue'
import Vuetify from 'vuetify/lib'

const veutifyObj = new Vuetify({
    theme: { dark: true },
});

Vue.use(VuetifyConfirm, { vuetify: veutifyObj })
```
